/*
 * AUSF API
 *
 * OpenAPI specification for AUSF
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ueauthentication

import (
	"free5gc/lib/http_wrapper"
	"free5gc/lib/openapi/models"
	"free5gc/src/ausf/handler"
	"free5gc/src/ausf/handler/message"
	"free5gc/src/ausf/logger"

	"github.com/gin-gonic/gin"
	// "fmt"
)

// EapAuthMethod -
func EapAuthMethod(c *gin.Context) {
	var eapSessionReq models.EapSession

	err := c.ShouldBindJSON(&eapSessionReq)
	if err != nil {
		logger.Auth5gAkaComfirmLog.Errorln(err)
	}

	req := http_wrapper.NewRequest(c.Request, eapSessionReq)
	req.Params["authCtxId"] = c.Param("authCtxId")

	handlerMsg := message.NewHandlerMessage(message.EventEapAuthComfirm, req)
	handler.SendMessage(handlerMsg)
	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// UeAuthenticationsAuthCtxId5gAkaConfirmationPut -
func UeAuthenticationsAuthCtxId5gAkaConfirmationPut(c *gin.Context) {
	var confirmationData models.ConfirmationData

	err := c.ShouldBindJSON(&confirmationData)
	if err != nil {
		logger.Auth5gAkaComfirmLog.Errorln(err)
	}

	req := http_wrapper.NewRequest(c.Request, confirmationData)
	req.Params["authCtxId"] = c.Param("authCtxId")

	handlerMsg := message.NewHandlerMessage(message.EventAuth5gAkaComfirm, req)
	handler.SendMessage(handlerMsg)
	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}

// UeAuthenticationsPost -
func UeAuthenticationsPost(c *gin.Context) {
	var authInfo models.AuthenticationInfo

	err := c.ShouldBindJSON(&authInfo)
	if err != nil {
		logger.UeAuthPostLog.Errorln(err)
	}

	req := http_wrapper.NewRequest(c.Request, authInfo)

	handlerMsg := message.NewHandlerMessage(message.EventUeAuthPost, req)
	handler.SendMessage(handlerMsg)
	rsp := <-handlerMsg.ResponseChan

	HTTPResponse := rsp.HTTPResponse
	HTTPRespHeader := rsp.HTTPResponse.Header
	for k, v := range HTTPRespHeader {
		c.Header(k, v[0])
	}
	c.JSON(HTTPResponse.Status, HTTPResponse.Body)
}
